### ISSUE TITLE
Lab 1 Report Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [AnnLe4869/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [] Lab report is on its own page, not the index page
 - You need to put the lab report on its own "lab_report_2.md" page or something like this (basically just separate from index.md please
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
- Table of contents and reference at the end was a nice addition! Excellent! 
- Looks great!  Just move to a separate markdown from index.md and well done! 

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by AnnLe4869** [comment]
Hi
I changed the file to the `lab-2-report.md` and update the link in `README.md`

**Comment by mrkylesmith** [comment]
Great, thanks for doing that.  Amazing lab report, well done!
